- dependency-manager/build.gradle.kts
- dependency-manager/src/main/kotlin/com/apgsga/maven/MavenBomManager.kt
- dependency-manager/src/main/kotlin/com/apgsga/maven/MavenBomManagerDefaultImpl.kt
- generic-publish/src/main/java/com/apgsga/gradle/publish/tasks/ApgPublishTask.java
- generic-publish/src/main/java/com/apgsga/gradle/repository/RepositoryBuilderFactory.java
@apgsga-jhe I made some changes, which effects your code. Therefore a pull request. 
Looks for details in code comments
> Refactored RepositoryBuilderFactory to accomodate more  usage scenarios

- testapp-service/build.gradle
@chhex : yeah, my modification have been done on the latest version, and not on 0.1. Ok for you if I change the plugin version within "testapp-service" ?
> IT-34988 / ApgGradlePlugin: verify test projects with new common-repo

- common-repo/src/functionalTest/groovy/com/apgsga/gradle/repo/plugin/BuildLogicFunctionalTest.groovy
- common-repo/src/main/java/com/apgsga/gradle/repo/extensions/AbstractRepo.java
- common-repo/src/main/java/com/apgsga/gradle/repo/extensions/RemoteRepo.java
- common-service-packager/src/functionalTest/groovy/com/apgsga/gradle/common/pkg/task/AppResourcesCopyTaskTests.groovy
- common-service-packager/src/functionalTest/groovy/com/apgsga/gradle/common/pkg/task/BinariesCopyTaskTests.groovy
- common-service-packager/src/functionalTest/groovy/com/apgsga/gradle/common/pkg/task/CopyResourcesToBuildDirActionTests.groovy
- common-service-packager/src/functionalTest/groovy/com/apgsga/gradle/common/pkg/task/PropertyFileMergeTasksTests.groovy
- common-service-packager/src/functionalTest/groovy/com/apgsga/gradle/common/pkg/task/TemplateDirCopyTaskTest.groovy
- common-test/src/main/groovy/com/apgsga/gradle/test/utils/AbstractSpecification.groovy
- dependency-manager/src/functionalTest/groovy/com/apgsga/gradle/maven/dm/BuildLogicFunctionalTest.groovy
- generic-publish/src/functionalTest/groovy/com/apgsga/gradle/publish/BuildLogicFunctionalTest.groovy
- it21-gui-packager/src/functionalTest/groovy/com/apgsga/gradle/gui/pkg/tasks/ZipPackageTaskTests.groovy
- maven-publish/src/functionalTest/groovy/com/apg/gradle/plugins/BuildLogicFunctionalTest.groovy
- repo-config/src/functionalTest/groovy/com/apgsga/gradle/repo/config/plugin/BuildLogicFunctionalTest.groovy
- rpm-service-packager/src/functionalTest/groovy/com/apgsga/gradle/rpm/pkg/tasks/BuildRpmTaskTests.groovy
- rpm-service-packager/src/functionalTest/groovy/com/apgsga/gradle/rpm/pkg/tasks/CopyResourcesToBuildDirActionTests.groovy
- rpm-service-packager/src/functionalTest/groovy/com/apgsga/gradle/rpm/pkg/tasks/RpmScriptsCopyTaskTests.groovy
- rpm-service-packager/src/functionalTest/groovy/com/apgsga/gradle/rpm/pkg/tasks/TemplateDirCopyTaskTest.groovy
- zip-service-packager/src/functionalTest/groovy/com/apgsga/gradle/zip/pkg/tasks/TarGzipTaskTests.groovy
Reading info from repoNames.json.
I'll also integrate the modifications suggested by @chhex within #7 ..... but this can already been reviewd.
One question ... : I find repoNames.json not a very good name anymore ... What do you think? What about "apgGradlePluginConfig.json" ?
> IT-34972 / user, pwd and repoName from JSON file

- common-repo/src/functionalTest/groovy/com/apgsga/gradle/repo/plugin/BuildLogicFunctionalTest.groovy
- common-repo/src/main/java/com/apgsga/gradle/repo/extensions/LocalRepo.java
- common-repo/src/main/java/com/apgsga/gradle/repo/extensions/RemoteRepo.java
- common-repo/src/main/java/com/apgsga/gradle/repo/extensions/Repo.java
- common-repo/src/main/java/com/apgsga/gradle/repo/extensions/RepoNames.java
- common-test/src/main/groovy/com/apgsga/gradle/test/utils/AbstractSpecification.groovy
- generic-publish/src/functionalTest/groovy/com/apgsga/gradle/publish/BuildLogicFunctionalTest.groovy
- generic-publish/src/main/java/com/apgsga/gradle/publish/tasks/ApgPublishTask.java
- generic-publish/src/main/java/com/apgsga/gradle/repository/artifactory/RemoteRepositoryBuilder.java
- maven-publish/src/functionalTest/groovy/com/apg/gradle/plugins/BuildLogicFunctionalTest.groovy
- maven-publish/src/main/java/com/apgsga/gradle/maven/publish/extension/ApgMavenPublishDsl.java
- repo-config/src/functionalTest/groovy/com/apgsga/gradle/repo/config/plugin/BuildLogicFunctionalTest.groovy
- repo-config/src/main/java/com/apgsga/gradle/repo/config/extensions/RepoConfig.java
As written in the ticket, we wantedto have a look at the PROS/CONS .... I would keep the ENUMs also in the build, although with out current usage we don't see a big impact.
> IT-35045 / APGGradlePlugin: common repo ENUM as Key for Repo Map

- common-repo/src/functionalTest/groovy/com/apgsga/gradle/repo/plugin/BuildLogicFunctionalTest.groovy
- common-repo/src/main/java/com/apgsga/gradle/repo/extensions/AbstractRepo.java
- common-repo/src/main/java/com/apgsga/gradle/repo/extensions/LocalRepo.java
- common-repo/src/main/java/com/apgsga/gradle/repo/extensions/RemoteRepo.java
- common-repo/src/main/java/com/apgsga/gradle/repo/extensions/RepoNames.java
- generic-publish/src/functionalTest/groovy/com/apgsga/gradle/publish/BuildLogicFunctionalTest.groovy
- generic-publish/src/main/java/com/apgsga/gradle/publish/tasks/ApgPublishTask.java
- generic-publish/src/main/java/com/apgsga/gradle/repository/RepositoryBuilderFactory.java
- maven-publish/src/main/java/com/apgsga/gradle/maven/publish/extension/ApgMavenPublishDsl.java
- repo-config/src/functionalTest/groovy/com/apgsga/gradle/repo/config/plugin/BuildLogicFunctionalTest.groovy
Tests are running fine locally. Some of them had to be adpated, but this was expected. I believe this is what we want, or at least I hope it went in the right direction ...
In any case, ready for a first review/comment/feedback ...
> IT-34974 / Consider LocalRepo same as RemoteRepo

- maven-publish/src/functionalTest/groovy/com/apg/gradle/plugins/BuildLogicFunctionalTest.groovy
- maven-publish/src/main/java/com/apgsga/gradle/maven/publish/extension/ApgMavenPublishDsl.java
I don't believe this is more complicated than that. What do you think?
(Side-note: test could be improved to check that the publish really occured at the right place. But in generall, we might want to double-check some tests anyway I believe.)
> IT-34788 / Add mavenLocal to maven-publish

- plugins/it21-gui-packager/src/functionalTest/groovy/com/apgsga/gradle/gui/pkg/tasks/ZipPackageTaskTests.groovy
- plugins/it21-gui-packager/src/main/groovy/com/apgsga/gradle/gui/pkg/tasks/ConfigureDepsTask.groovy
- plugins/it21-gui-packager/src/main/groovy/com/apgsga/gradle/gui/pkg/tasks/DllCopyTask.groovy
- plugins/it21-gui-packager/src/main/groovy/com/apgsga/gradle/gui/pkg/tasks/JarCopyTask.groovy
- plugins/it21-gui-packager/src/main/java/com/apgsga/gradle/gui/pkg/extension/ApgGuiPackageExtension.java
I believe this should be fine, at least the test still runs ok ...
@apgsga-stb , @apgsga-uge : FYI
@chhex : I need your review ;)
> IT-35245 / it21-gui-packager make configuration name configureable

- plugins/rpm-ssh-deployer/src/functionalTest/groovy/com/apgsga/gradle/ssh/plugin/BuildLogicFunctionalTests.groovy
- plugins/rpm-ssh-deployer/src/main/groovy/com/apgsga/gradle/ssh/tasks/AbstractRpm.groovy
- plugins/rpm-ssh-deployer/src/main/groovy/com/apgsga/gradle/ssh/tasks/DeployRpm.groovy
- plugins/rpm-ssh-deployer/src/main/groovy/com/apgsga/gradle/ssh/tasks/InstallRpm.groovy
- plugins/rpm-ssh-deployer/src/main/java/com/apgsga/gradle/ssh/plugin/ApgRpmSshDeployer.java
Ready for a review.
Not sure the abstract class is the best, maybe even possible to factore out more code, but probably ok for now.
@apgsga-stb , @apgsga-uge : FYI
> IT-35448 / splitting deploy rpm into 2 tasks: deploy and install

- plugins/rpm-ssh-deployer/src/main/groovy/com/apgsga/gradle/ssh/tasks/InstallRpm.groovy
Tested OK against jenkins-t.
@chhex : No big deal for the PullRequest I believe, we need to see how we want to backport it on Digiflex ... or if we want to build a new version for Digiflex. But as you wrote me in an Email, we need to discuss it (I'll send you an Outlook Meeting soon :) )
@apgsga-uge , @apgsga-stb : FYI
> IT-35393 / RPM removed after having been installed

- plugins/gradle-common/common-plugin.gradle
Shouldn't be more complicated than that for our apg-gradle-plugin Build, I believe.
@apgsga-stb , @apgsga-uge  : FYI
> IT-34784: getting credentials from Studer-Plugin

- integration/jenkins-pipeline-tests/build.gradle
- integration/jenkins-pipeline-tests/buildSrc/build.gradle.kts
- integration/jenkins-pipeline-tests/jenkinsPkgAndDeploy/Jenkinsfile
- integration/modules/testapp-pkg/build.gradle
- integration/modules/testapp-pkg/buildRpm.sh
No ticket has been created for this one, this is basically adaptation done after having merged IT-35559 and IT-35546.
See also come comments in the code.
You also might want to pull the latest from git.apgsga.ch:/var/git/repos/apg-gradle-properties.git
> adaptations for new ssh-tasks plugin

- plugins/revision-manager/src/integrationTest/groovy/com/apgsga/revision/manager/domain/RevisionManagerLocalPersistenceTests.groovy
- plugins/revision-manager/src/main/groovy/com/apgsga/revision/manager/domain/RevisionManager.groovy
- plugins/revision-manager/src/main/groovy/com/apgsga/revision/manager/domain/RevisionManagerBuilder.groovy
- plugins/revision-manager/src/main/groovy/com/apgsga/revision/manager/domain/RevisionManagerPatchImpl.groovy
- plugins/revision-manager/src/main/groovy/com/apgsga/revision/manager/domain/RevisionManagerSnapshotImpl.groovy
- plugins/revision-manager/src/main/groovy/com/apgsga/revision/manager/persistence/RevisionBeanBackedPersistence.groovy
- plugins/revision-manager/src/main/groovy/com/apgsga/revision/manager/persistence/RevisionPersistence.groovy
- plugins/revision-manager/src/main/groovy/com/apgsga/revision/manager/persistence/RevisionTargetHistory.groovy
- plugins/revision-manager/src/main/groovy/com/apgsga/revision/manager/persistence/Revisions.groovy
- plugins/version-manager/src/main/kotlin/com/apgsga/maven/dm/ext/VersionResolution.kt
Ready for a review ... As soon as the review is fine, I'll also create additional test cases (I believe we should better cover with additional scenario), maybe I'll create a new ticket for that.
See the modification done for the "VersionResolution.kt" file. I did it just that it compiles, but I believe the "VersionResolution" extension should have a "serviceName" parameter, what do you think?
> IT-35566 / Revision Tracking must support Multiservices

- integration/digiflex/digiflex-it21-ui-pkg/build.gradle
- plugins/ssh-tasks/src/main/groovy/com/apgsga/ssh/zip/tasks/InstallZip.groovy
@chhex : JFYI, this is a pull request in order to track changes made for IT-35824. I'll merge it immediately.
> IT-35824 / Digiflex-ui

- plugins/version-manager/build.gradle.kts
- plugins/version-manager/src/integrationTest/groovy/com/apgsga/maven/impl/resolver/CompositeVersionResolverDefaultTest.groovy
- plugins/version-manager/src/integrationTest/resources/patchresolvertests/PatchA5791.json
- plugins/version-manager/src/integrationTest/resources/patchresolvertests/PatchB5402.json
- plugins/version-manager/src/integrationTest/resources/patchresolvertests/PatchZ5401.json
@chhex : A quick one, our plugin should use our latest Piper Version ...
> IT-36059 / Using latest version of Piper

- plugins/gradle-common/common-plugin.gradle
- plugins/revision-manager/src/main/groovy/com/apgsga/revision/manager/domain/RevisionManagerPatchImpl.groovy
- plugins/version-manager/src/main/kotlin/com/apgsga/maven/dm/ext/VersionResolution.kt
- plugins/version-manager/src/main/kotlin/com/apgsga/maven/impl/resolver/MavenArtifactListResolver.kt
- plugins/version-manager/src/main/kotlin/com/apgsga/maven/impl/resolver/ResolverBuilder.kt
- plugins/version-manager/src/main/kotlin/com/apgsga/maven/impl/resolver/SingleArtifactResolver.kt
@apgsga-jhe You can already give feedback .... 
I ll be taking on IT-36332 for Testcases
> Bom update artifact version

- plugins/revision-manager/src/integrationTest/groovy/com/apgsga/revision/manager/domain/RevisionManagerLocalPersistenceTests.groovy
> Bom update artifact version Update

- plugins/ssh-tasks/src/functionalTest/groovy/com/apgsga/ssh/zip/BuildLogicZipFunctionalTests.groovy
- plugins/ssh-tasks/src/main/groovy/com/apgsga/ssh/zip/tasks/AbstractZip.groovy
- plugins/ssh-tasks/src/main/groovy/com/apgsga/ssh/zip/tasks/DeployZip.groovy
- plugins/ssh-tasks/src/main/java/com/apgsga/ssh/extensions/ApgZipDeployConfig.java
Unused properties for deployZip removed.
@chhex  : If OK for you, I'll merge this one immediately.
> IT-36306 - 2 / provide a minimal IT21-UI to test Gradle-Plugin

- plugins/gradle-common/common-plugin.gradle
- plugins/ssh-tasks/src/main/groovy/com/apgsga/ssh/zip/tasks/AbstractZip.groovy
- plugins/ssh-tasks/src/main/groovy/com/apgsga/ssh/zip/tasks/DeployZip.groovy
- plugins/ssh-tasks/src/main/groovy/com/apgsga/ssh/zip/tasks/InstallZip.groovy
installZip part adapted to match other modification -> getting the correct zip file name, centralized from the common-packager.
> IT-36306 - 3 / provide a minimal IT21-UI to test Gradle-Plugin

- plugins/gradle.properties
- plugins/version-manager/src/main/kotlin/com/apgsga/maven/dm/plugin/VersionResolutionPlugin.kt
- plugins/version-manager/src/main/kotlin/com/apgsga/maven/impl/resolver/AbstractVersionResolver.kt
- plugins/version-manager/src/main/kotlin/com/apgsga/maven/impl/resolver/MavenArtifactListResolver.kt
See Issues 
IT-36344 :  Apg Gradle Dependency Resolution, log warning when duplicate artifactids found
IT-36343 :  Apg Gradle Dependency Resolution should have better logging
> Version Resolver Logging and Check for Duplicates

- plugins/revision-manager/src/main/groovy/com/apgsga/revision/manager/persistence/RevisionBeanBackedPersistence.groovy
- plugins/revision-manager/src/main/groovy/com/apgsga/revision/manager/persistence/RevisionsHistory.groovy
- plugins/revision-manager/src/test/groovy/com/apgsga/revision/manager/domain/RevisionManagerLocalPersistenceTests.groovy
@chhex , @apgsga-uge 
A small one in order to renamed RevisionTargetHistory.json into RevisionsHistory.json.
I'll merge immediately.
> IT-36961 / RevisionTargetHistory.json should be RevisionsHistory.json
